language: node_js

node_js:
  - node

os: linux

install:
  - gem install bundler
  - bundle install
  - npm install -g gulp
  - npm install

# add tests
script:
  - gulp lint
  - gulp build

branches:
  only:
    - master

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: _site
  keep-history: true
  on:
    branch: master
  repo: simplyRoba/bumpels_site
  target_branch: master
  fqdn: bumpels.de