# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bumpels
author: Axel Rojas Bachem
email: webmaster@bumpels.de
description: > # this means to ignore newlines until "baseurl:"
  Bumpels are Kumpels.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bumpels.de" # the base hostname & protocol for your site, e.g. http://example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - news.md
  - gallery.md
  - merch.md
  - about.md

show_excerpts: true

# Basic settings
encoding: "utf-8"
timezone: Europe/Berlin
date_format: "%b %-d, %Y" # refer to http://shopify.github.io/liquid/filters/date/ 
google_analytics: UA-113534066-1

# default front matter settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->
      categories: news
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->
      categories: news
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
