
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Some General settings and data for SEO
title: Bumpels
author: Axel Rojas Bachem
email: webmaster@bumpels.de
description: > # this means to ignore newlines until "baseurl:"
  Home of the Bumpels. 
  Bumpels are sweet little creatures. There are many different ones and all of them want new friends.
lang: en_UK
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.bumpels.de # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/img/logo.svg
twitter: # site-wide twitter account in seo
  username: simplyRoBa
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234

# Basic settings
encoding: "utf-8"
timezone: Europe/Berlin
date_format: "%a, %e. %b %y" # refer to http://shopify.github.io/liquid/filters/date/ 
google_analytics: UA-113534066-1
permalink: /:categories/:year/:month/:day/:title/
header_pages: # list of header navigation entries
  - news.md
  - gallery.md
  - merch.md
  - about.md
show_excerpts: true
theme: # try to not use a theme ...

# default front matter settings
defaults:
  - 
    scope: # defaults for ALL sites
      path: ""
    values:
      author: Axel Rojas Bachem
      image: 
        path: /assets/img/logo.svg
        height: 300
        width: 300
  -
    scope: # defaults for drafts
      path: ""
      type: drafts
    values:
      layout: post
      excerpt_separator: <!--more-->
      categories: news
  -
    scope: # defaults for posts
      path: ""
      type: posts
    values:
      layout: post
      excerpt_separator: <!--more-->
      categories: news
  -
    scope: # defaults for pages
      path: ""
      type: pages
    values:
      layout: page

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - tsconfig.json
  - gulpfile.js
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
