# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, test and deploy

on: 
  push :
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install & Build 
      run: |
        npm install -g gatsby-cli
        npm ci
        npm run clean
        npm run build
    - name: Test
      run: npm run test
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9 # https://github.com/marketplace/actions/deploy-to-github-pages
      with:
        ACCESS_TOKEN: ${{ secrets.BUMPELS_SITE_ACCESS_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: public # The folder the action should deploy.
        REPOSITORY_NAME: simplyRoba/bumpels_site # Repository name 
        SINGLE_COMMIT: false # Do maintain history on target branch

