# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and test

on: 
  push :
    branches-ignore: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install & Build 
      run: |
        npm install -g gatsby-cli
        npm ci
        npm run clean
        npm run build
    - name: Test
      run: npm run test
